import os
import json
import requests

project_type = "webapp"
tech_stack = "react"
requirements = "シンプルなToDoアプリ"

headers = {
    "x-api-key": os.environ["ANTHROPIC_API_KEY"],
    "content-type": "application/json",
    "anthropic-version": "2023-06-01"
}

prompt = f"""新しい{project_type}プロジェクトを作成してください。

プロジェクト情報:
- タイプ: {project_type}
- 技術スタック: {tech_stack}
- 要件: {requirements}

以下を実装してください:
1. 適切なプロジェクト構造
2. 基本的な設定ファイル
3. エントリーポイントとサンプルコード
4. README.mdファイル
5. 要件に応じた基本機能

ファイルを作成してコミットしてください。"""

data = {
    "model": "claude-3-sonnet-20240229",
    "max_tokens": 4000,
    "messages": [
        {"role": "user", "content": prompt}
    ]
}

try:
    response = requests.post(
        "https://api.anthropic.com/v1/messages",
        headers=headers,
        json=data,
        timeout=30
    )
    
    if response.status_code == 200:
        result = response.json()
        content = result["content"][0]["text"]
        print("Claude response received successfully")
        
        with open("generation_summary.txt", "w", encoding="utf-8") as f:
            f.write("Project generated successfully by Claude AI")
            
        # 基本的なプロジェクトファイルを作成
        with open("README.md", "w", encoding="utf-8") as f:
            f.write(f"# {project_type.title()} Project\n\n")
            f.write(f"Technology Stack: {tech_stack}\n\n")
            f.write(f"Requirements: {requirements}\n\n")
            f.write("Generated by Claude AI\n")
            
    else:
        print(f"API Error: {response.status_code}")
        with open("generation_summary.txt", "w") as f:
            f.write(f"API Error: {response.status_code}")
            
except Exception as e:
    print(f"Error: {e}")
    with open("generation_summary.txt", "w") as f:
        f.write(f"Error: {e}")
